#ifndef DIALOG_H
#define DIALOG_H

#include <QDialog>
#include <QTimer>
#include <QLCDNumber>
#include <QGraphicsScene>
#include <QGraphicsView>
#include "team.h"
#include "Ball.h"

QT_BEGIN_NAMESPACE
namespace Ui {
class Dialog;
}
QT_END_NAMESPACE

// Dialog class that extends QDialog to provide a user interface for the game.
class Dialog : public QDialog
{
    Q_OBJECT

public:
    explicit Dialog(QWidget *parent = nullptr); // Constructor
    ~Dialog(); // Destructor

public slots:
    void AddGoal1Score();       // Slot to add score for Team1
    void AddGoal2Score();       // Slot to add score for Team2
    void updateGame();          // Slot to update game entities and logic
    void resetPlayers();        // Slot to reset the players' positions
    void updateGameClock();     // Slot to update the game clock every second

private:
    Ui::Dialog *ui;                       // User interface generated by Qt Designer
    QGraphicsScene *scene;                // Scene for rendering game graphics
    QTimer *timer;                        // Timer for the main game loop
    QTimer *gameClockTimer;               // Timer for the game clock
    QLCDNumber *gameClockDisplay;         // Display for the game clock
    int gameSecondsElapsed;               // Counter of seconds elapsed in the game

    Team *team1;                          // Team1 object
    Team *team2;                          // Team2 object
    int Goal1Score = 0;                   // Score of Team1
    int Goal2Score = 0;                   // Score of Team2
    Ball *ball;                           // Ball object
};

#endif // DIALOG_H
