#ifndef MAINWINDOW_H
#define MAINWINDOW_H

#include <QMainWindow>
#include "dialog.h"
#include "Ball.h"

QT_BEGIN_NAMESPACE
namespace Ui {
class MainWindow;
}
QT_END_NAMESPACE

// MainWindow class, responsible for the main window of the application.
class MainWindow : public QMainWindow
{
    Q_OBJECT // Qt macro to enable slots and signals.

public:
    // Constructor
    // parent: The parent widget of this window, usually null for the main window.
    MainWindow(QWidget *parent = nullptr);

    // Destructor
    ~MainWindow();

private slots:
    // Slot to handle the button click event.
    // This slot is connected to the click signal of a QPushButton in the user interface.
    void on_pushButton_clicked();

private:
    Ui::MainWindow *ui; // Pointer to the user interface generated by uic from the .ui file.
    Ball *ball; // Pointer to the instance of the ball used in the game.
    Dialog *dialog; // Pointer to an instance of Dialog, which manages the game logic and presentation.
};
#endif // MAINWINDOW_H
